export const FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAILURE = "FETCH_ARTICLES_FAILURE";
export const FETCH_ARTICLES_CLEAR = "FETCH_ARTICLES_CLEAR";

export const FETCH_ARTICLE_REQUEST = "FETCH_ARTICLE_REQUEST";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_FAILURE = "FETCH_ARTICLE_FAILURE";
export const FETCH_ARTICLE_CLEAR = "FETCH_ARTICLE_CLEAR";

export const EDIT_ARTICLE_REQUEST = "EDIT_ARTICLE_REQUEST";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_FAILURE = "EDIT_ARTICLE_FAILURE";
export const EDIT_ARTICLE_CLEAR = "EDIT_ARTICLE_CLEAR";

export const REMOVE_ARTICLE_REQUEST = "REMOVE_ARTICLE_REQUEST";
export const REMOVE_ARTICLE_SUCCESS = "REMOVE_ARTICLE_SUCCESS";
export const REMOVE_ARTICLE_FAILURE = "REMOVE_ARTICLE_FAILURE";
export const REMOVE_ARTICLE_CLEAR = "REMOVE_ARTICLE_CLEAR";

export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAILURE = "ADD_ARTICLE_FAILURE";
export const ADD_ARTICLE_CLEAR = "ADD_ARTICLE_CLEAR";
